# btop theme: black_red
# Copyright (c) 2026  Chris McGimpsey-Jones <chrisjones.unixmen@gmail.com>
# SPDX-License-Identifier: MIT

theme[main_bg]="#000000"
theme[main_fg]="#FFFFFF"
theme[hi_fg]="#FF0000"
theme[inactive_fg]="#9AA0A6"
theme[graph_text]="#FFFFFF"
theme[div_line]="#1F1F1F"

theme[cpu_box]="#FF0000"
theme[mem_box]="#FF0000"
theme[net_box]="#FF0000"
theme[proc_box]="#FF0000"

theme[title]="#FFFFFF"
theme[selected_bg]="#220000"
theme[selected_fg]="#FFFFFF"

theme[temp_start]="#000000"
theme[temp_mid]="#FF0000"
theme[temp_end]="#FF0000"
theme[symbols]="#FF0000"
theme[clock_dot]="#FF0000"

theme[cpu_start]="#000000"
theme[cpu_mid]="#FF0000"
theme[cpu_end]="#FF0000"

theme[free_start]="#000000"
theme[free_mid]="#FF0000"
theme[free_end]="#FF0000"
theme[cached_start]="#000000"
theme[cached_mid]="#FF0000"
theme[cached_end]="#FF0000"
theme[available_start]="#000000"
theme[available_mid]="#FF0000"
theme[available_end]="#FF0000"
theme[used_start]="#000000"
theme[used_mid]="#FF0000"
theme[used_end]="#FF0000"

theme[download_start]="#000000"
theme[download_mid]="#FF0000"
theme[download_end]="#FF0000"
theme[upload_start]="#000000"
theme[upload_mid]="#FF0000"
theme[upload_end]="#FF0000"

theme[proc_misc]="#FF0000"
theme[process_start]="#FF0000"
theme[process_mid]="#FF0000"
theme[process_end]="#FF0000"

theme[meter_bg]="#333333"
